# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /workspaces/Edgeist

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /workspaces/Edgeist

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /workspaces/Edgeist/CMakeFiles /workspaces/Edgeist//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /workspaces/Edgeist/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /workspaces/Edgeist/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named edgeist-desktop

# Build rule for target.
edgeist-desktop: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 edgeist-desktop
.PHONY : edgeist-desktop

# fast build rule for target.
edgeist-desktop/fast:
	$(MAKE) $(MAKESILENT) -f desktop_application/CMakeFiles/edgeist-desktop.dir/build.make desktop_application/CMakeFiles/edgeist-desktop.dir/build
.PHONY : edgeist-desktop/fast

#=============================================================================
# Target rules for targets named boost_assert

# Build rule for target.
boost_assert: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 boost_assert
.PHONY : boost_assert

# fast build rule for target.
boost_assert/fast:
	$(MAKE) $(MAKESILENT) -f _deps/boost-build/libs/assert/CMakeFiles/boost_assert.dir/build.make _deps/boost-build/libs/assert/CMakeFiles/boost_assert.dir/build
.PHONY : boost_assert/fast

#=============================================================================
# Target rules for targets named boost_container

# Build rule for target.
boost_container: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 boost_container
.PHONY : boost_container

# fast build rule for target.
boost_container/fast:
	$(MAKE) $(MAKESILENT) -f _deps/boost-build/libs/container/CMakeFiles/boost_container.dir/build.make _deps/boost-build/libs/container/CMakeFiles/boost_container.dir/build
.PHONY : boost_container/fast

#=============================================================================
# Target rules for targets named boost_optional

# Build rule for target.
boost_optional: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 boost_optional
.PHONY : boost_optional

# fast build rule for target.
boost_optional/fast:
	$(MAKE) $(MAKESILENT) -f _deps/boost-build/libs/optional/CMakeFiles/boost_optional.dir/build.make _deps/boost-build/libs/optional/CMakeFiles/boost_optional.dir/build
.PHONY : boost_optional/fast

#=============================================================================
# Target rules for targets named boost_program_options

# Build rule for target.
boost_program_options: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 boost_program_options
.PHONY : boost_program_options

# fast build rule for target.
boost_program_options/fast:
	$(MAKE) $(MAKESILENT) -f _deps/boost-build/libs/program_options/CMakeFiles/boost_program_options.dir/build.make _deps/boost-build/libs/program_options/CMakeFiles/boost_program_options.dir/build
.PHONY : boost_program_options/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... boost_assert"
	@echo "... boost_container"
	@echo "... boost_optional"
	@echo "... boost_program_options"
	@echo "... edgeist-desktop"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /workspaces/Edgeist/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

