/**
 * @brief Autogenerated by CMake, contains version and revision info.
 * @file
 * @author Daniel Giritzer, MSc
 * @copyright Restricted
 */
#ifndef Edgeist_Edgeist_CONFIG_H
#define Edgeist_Edgeist_CONFIG_H
#include <cstddef>
/**
 * @brief The projects namespace
 */
namespace Edgeist{
    /**
     * @brief The Edgeist component namespace
     */
    namespace Edgeist{
    constexpr size_t VERSION_MAJOR = 0; ///< The projects major number
    constexpr size_t VERSION_MINOR = 0; ///< The projects minor number
    constexpr size_t VERSION_PATCH = 0; ///< The projects patch number
    constexpr size_t VERSION_TWEAK = 10000; ///< The projects tweak number
    constexpr char const* const BUILD_TIMESTAMP = "2026-05-18T12:56:28"; ///< The projects build timestamp
    constexpr char const* const COMMIT_HASH = "ee2dd8920404badc5818d2ef629940b46c650d7a (DIRTY)"; ///< The projects git revision

    /**
     * @brief Enum which can be used to check the projects build type.
     * @see BUILD_TYPE
     */
    enum class BuildType {
        Debug = 0, ///< Debug build
        Release = 1, ///< Optimized Release build
        MinSizeRel = 2, ///< Build optimized for size
        RelWithDebInfo = 3 ///< Optimized Release build containing debug info
    };

    /**
     * @brief This variable is set to the build type of the project.
     */
    constexpr BuildType BUILD_TYPE = BuildType::RelWithDebInfo;
    }
}
#endif // Edgeist_Edgeist_CONFIG_H
