import os


class HeaderWriter:
    #: defines the spaces used instead of a tab as according to the clang-format rules.
    _TAB = "    "
    #: defines the name of the namespace wrapping all generated code.
    _WRAPPER_NAMESPACE = "Nmcm"

    @staticmethod
    def _generate_header_doc(text: str) -> str:
        """Generates the files doxygen header.

        :param text: A brief description of the purpose of the file
        :returns: The doxygen header of the file
        """
        return f"""\
/**
 * @file
 * @brief {text}
 * @warning Autogenerated file: DO NOT EDIT
 */

"""

    @staticmethod
    def _generate_include_guard_name(file_name: str) -> str:
        """Generates the include guard name.

        :param file_name: The name of the file
        :returns: The name generated guard name
        """
        return f"NMCM_{file_name.upper()}_H"

    @staticmethod
    def _begin_include_guards(guard_name: str) -> str:
        """Generates the begin of the files include guard.

        :param guard_name: The name of the include guard
        :returns: The string beginning the include guard
        """
        return f"""\
#ifndef {guard_name}
#define {guard_name}

"""

    @staticmethod
    def _end_include_guards(guard_name: str) -> str:
        """Generates the string ending the files include guard.

        :param: The name of the include guard
        :returns: The string ending the include guard
        """
        return f"#endif // {guard_name}"

    @staticmethod
    def _begin_namespace(namespace: str) -> str:
        """Creates the string for beginning the namespace.

        :param namespace: The name of the namespace
        :returns: The namespace string
        """
        return f"namespace {namespace} {{\n"

    @staticmethod
    def _end_namespace(namespace: str) -> str:
        """Creates the string for ending the namespace.

        :param namespace: The name of the namespace
        :returns: The namespace string
        """
        return f"}} // namespace {namespace}\n"

    @staticmethod
    def _generate_brief(text: str) -> str:
        return f"""\
/**
 * @brief {text} 
 */
"""

    @staticmethod
    def _camel_to_pascal_case(value: str) -> str:
        """Converts a camel case string to a pascal case string.

        :param value: The string to convert
        :returns: The converted string
        """
        if len(value) == 0:
            return ""

        return value[0].upper() + value[1:]

    def __init__(self, typefile: str, structfile: str, enumfile: str):
        """
        Constructor of the class HeaderWriter

        Checks fileending is valid .h

        Parameters:
        file (str): filename and path e.g. ./test.h

        Raises:
        File is no .h: If file ends not with .h
        """
        # init h File
        self.type_file = typefile
        self.type_filename = os.path.basename(typefile).split(".")[0]

        if self.type_file.split(".")[-1] != "h":
            raise ValueError(f"Type-file '{self.type_file}' is missing the '.h' file extension")

        self.struct_file = structfile
        self.struct_filename = os.path.basename(structfile).split(".")[0]

        if self.struct_file.split(".")[-1] != "h":
            raise ValueError(f"Struct-file '{self.struct_file}' is missing the '.h' file extension")

        self.enum_file = enumfile
        self.enum_filename = os.path.basename(enumfile).split(".")[0]

        if self.enum_file.split(".")[-1] != "h":
            raise ValueError(f"Enum-file '{self.enum_file}' is missing the '.h' file extension")

    def write(self, config):
        """
        Creates or clears the outputfile.
        writes all types and the version from the config
        to the outputfile in c++ style

        Parameters:
        config (dic): data of the configfile as dictionary
        """
        self._write_type_header(config)
        self._write_struct_header(config)
        self._write_enum_header()

    # Helper function to map the typenames to cpp compatible ones
    def _map_to_cpp_type(self, typename: str) -> str:
        mapping = {
            "float32_t": "float",
            "float64_t": "double",
            "float16_t": "uint16_t",
            "int8_t": "int8_t",
            "uint8_t": "uint8_t",
            "int16_t": "int16_t",
            "uint16_t": "uint16_t",
            "int32_t": "int32_t",
            "uint32_t": "uint32_t",
            "int64_t": "int64_t",
            "uint64_t": "uint64_t",
        }
        if typename not in mapping:
            raise ValueError(f"Unknown type '{typename}'")
        return mapping.get(typename, typename)

    def _write_type_header(self, config):
        with open(self.type_file, "w") as outfile:
            guard_name = HeaderWriter._generate_include_guard_name(self.type_filename)
            outfile.write(
                HeaderWriter._generate_header_doc("Defines the required types for interfacing the neural network")
            )
            outfile.write(HeaderWriter._begin_include_guards(guard_name))
            outfile.write("#include <cstdint>\n\n")
            outfile.write(HeaderWriter._begin_namespace(HeaderWriter._WRAPPER_NAMESPACE))

            for index, (key, _) in enumerate(config.items()):
                if key == "Offset_Table":
                    continue

                if key == "Config-Info":
                    # this section has no types but the version string
                    outfile.write(f"// {key}-types\n")
                    outfile.write(f'constexpr auto* VERSION_STR = "' + config[key]["version"][1] + '";\n')
                    outfile.write(f"using Id = {config[key]['id'][1]};\n")
                    outfile.write(f"using OffsetTableEntry = {config[key]['Offset_Table'][1]};\n")
                else:
                    outfile.write(f"// {key}-types\n")
                    # write datatypes
                    types = config[key]
                    if len(types) > 0:
                        outfile.write(HeaderWriter._begin_namespace(key))
                        for name, typeinfo in config[key].items():
                            mapped_type = self._map_to_cpp_type(typeinfo[1])
                            outfile.write(
                                f"{HeaderWriter._TAB}using {HeaderWriter._camel_to_pascal_case(name)} = {mapped_type};\n"
                            )
                        outfile.write(HeaderWriter._end_namespace(key))
                if index < (len(config) - 1):
                    outfile.write("\n")

            outfile.write(HeaderWriter._end_namespace(HeaderWriter._WRAPPER_NAMESPACE))
            outfile.write(HeaderWriter._end_include_guards(guard_name))

    def _write_struct_header(self, config):
        with open(self.struct_file, "w") as outfile:
            guard_name = HeaderWriter._generate_include_guard_name(self.struct_filename)
            outfile.write(
                HeaderWriter._generate_header_doc("Defines the required structs for interfacing the neural network")
            )
            outfile.write(HeaderWriter._begin_include_guards(guard_name))
            outfile.write(f"#include <array>\n\n")
            outfile.write(f'#include "{self.type_filename}.h"\n\n')
            outfile.write(HeaderWriter._begin_namespace(HeaderWriter._WRAPPER_NAMESPACE))

            for index, (key, _) in enumerate(config.items()):
                if key != "Config-Info" and key != "Offset_Table":
                    outfile.write(HeaderWriter._begin_namespace(key))
                    outfile.write(HeaderWriter._generate_brief(f"Defines the required structure for {key}"))
                    outfile.write("#pragma pack(push, 1)\n")
                    outfile.write(f"{HeaderWriter._TAB}struct NeuralNetwork {{\n")

                    for name, typeinfo in config[key].items():
                        pascal_case = HeaderWriter._camel_to_pascal_case(name)
                        if typeinfo[0] == 1:
                            outfile.write(f"{HeaderWriter._TAB*2}{pascal_case} {name};\n")
                        elif typeinfo[0] == 0:
                            # should be a pointer
                            outfile.write(f"{HeaderWriter._TAB*2}{pascal_case}* {name};\n")
                        else:
                            outfile.write(
                                f"{HeaderWriter._TAB*2}std::array<{pascal_case}, {str(typeinfo[0])}> {name}; // NOLINT(*-magic-numbers)\n"
                            )

                    outfile.write(f"{HeaderWriter._TAB} }};\n")
                    outfile.write("#pragma pack(pop)\n")
                    outfile.write(HeaderWriter._end_namespace(key))
                    if index < (len(config) - 1):
                        outfile.write("\n")

            outfile.write(HeaderWriter._end_namespace(HeaderWriter._WRAPPER_NAMESPACE))
            outfile.write(HeaderWriter._end_include_guards(guard_name))

    # write all IDs of the Layers in ./Layers
    def _write_enum_header(self):
        from nmcm_common.layers import LAYERS
        from nmcm_common.utils.datatype import Datatype

        types = Datatype.get_all_datatypes()

        with open(self.enum_file, "w") as outfile:
            guard_name = HeaderWriter._generate_include_guard_name(self.enum_filename)

            outfile.write(
                HeaderWriter._generate_header_doc("Defines the required enums for interfacing the neural network")
            )
            outfile.write(HeaderWriter._begin_include_guards(guard_name))
            outfile.write(f"#include <cstdint>\n\n")
            outfile.write(HeaderWriter._begin_namespace(HeaderWriter._WRAPPER_NAMESPACE))

            # DataEncodingIDs
            outfile.write(HeaderWriter._generate_brief("Defines all data encoding IDs"))
            outfile.write("enum class DataEncodingId : uint8_t {\n")
            for val in types:
                outfile.write(f"{HeaderWriter._TAB}{Datatype.get_str(val).removesuffix("_t").title()} = {str(val)},\n")
            outfile.write("};\n\n")

            outfile.write(HeaderWriter._generate_brief("Defines all layer IDs"))
            outfile.write("enum class LayerId : uint8_t {\n")
            for layer in LAYERS:
                outfile.write(f"{HeaderWriter._TAB}{layer.__name__} = {layer.LAYER_ID},\n")

            outfile.write("};\n")
            outfile.write(HeaderWriter._end_namespace(HeaderWriter._WRAPPER_NAMESPACE))
            outfile.write(HeaderWriter._end_include_guards(guard_name))
