function(edgeist_apply_common_options target_name)
    target_compile_features(${target_name} PUBLIC cxx_std_20)

    if(MSVC)
        target_compile_options(${target_name} PRIVATE /W4 /permissive-)
        if(EDGEIST_DETERMINISTIC_MATH)
            target_compile_options(${target_name} PRIVATE /fp:strict)
        endif()
    else()
        target_compile_options(${target_name} PRIVATE -Wall -Wextra -Wpedantic -Wconversion -Wshadow)
        if(EDGEIST_DETERMINISTIC_MATH)
            target_compile_options(${target_name} PRIVATE -ffp-contract=off -fno-fast-math)
        endif()
        if(NOT EDGEIST_ENABLE_EXCEPTIONS)
            target_compile_options(${target_name} PRIVATE -fno-exceptions)
        endif()
        if(EDGEIST_ENABLE_ASAN)
            target_compile_options(${target_name} PRIVATE -fsanitize=address -fno-omit-frame-pointer)
            target_link_options(${target_name} PRIVATE -fsanitize=address)
        endif()
        if(EDGEIST_ENABLE_UBSAN)
            target_compile_options(${target_name} PRIVATE -fsanitize=undefined -fno-omit-frame-pointer)
            target_link_options(${target_name} PRIVATE -fsanitize=undefined)
        endif()
    endif()
endfunction()
